source 'https://rubygems.org'
gem 'json'
gem 'rack'
gem 'rack-cors'
gem 'rack-contrib'
gem 'grape'
gem 'grape-swagger', :git => 'https://github.com/tim-vandecasteele/grape-swagger.git'
gem 'grape-entity'
gem 'grape_logging'
gem 'activerecord'
gem 'grape-activerecord'
gem 'mysql2'
gem 'rest-client'
gem 'google-api-client'
